/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantsytem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class log extends javax.swing.JFrame {

    /**
     * Creates new form log
     */
    public log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        s1 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        k1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        userTF = new javax.swing.JTextField();
        passTF = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userTF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\user-group-icon.png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        a1.setBackground(new java.awt.Color(74, 31, 61));
        a1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setText("Ad Soyad");
        a1.setBorder(null);
        a1.setCaretColor(new java.awt.Color(255, 255, 255));
        a1.setCaretPosition(8);
        a1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                a1FocusGained(evt);
            }
        });
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel2.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, 30));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        s1.setBackground(new java.awt.Color(74, 31, 61));
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("Şifre");
        s1.setBorder(null);
        s1.setCaretColor(new java.awt.Color(255, 255, 255));
        s1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s1FocusGained(evt);
            }
        });
        jPanel2.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\unlocked-icon.png")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 40));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("        Kayıt ol");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 100, 40));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 282, 250, 10));

        k1.setBackground(new java.awt.Color(74, 31, 61));
        k1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        k1.setForeground(new java.awt.Color(255, 255, 255));
        k1.setText("Kullanıcı adı");
        k1.setBorder(null);
        k1.setCaretColor(new java.awt.Color(255, 255, 255));
        k1.setCaretPosition(8);
        k1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                k1FocusGained(evt);
            }
        });
        k1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k1ActionPerformed(evt);
            }
        });
        jPanel2.add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\person-icon.png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 30, 40));

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTF.setBackground(new java.awt.Color(186, 79, 84));
        userTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userTF.setForeground(new java.awt.Color(255, 255, 255));
        userTF.setText("Kullanıcı adı");
        userTF.setBorder(null);
        userTF.setCaretColor(new java.awt.Color(255, 255, 255));
        userTF.setCaretPosition(8);
        userTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTFFocusGained(evt);
            }
        });
        userTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTFActionPerformed(evt);
            }
        });
        jPanel3.add(userTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        passTF.setBackground(new java.awt.Color(186, 79, 84));
        passTF.setForeground(new java.awt.Color(255, 255, 255));
        passTF.setText("Şifre");
        passTF.setBorder(null);
        passTF.setCaretColor(new java.awt.Color(255, 255, 255));
        passTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTFFocusGained(evt);
            }
        });
        jPanel3.add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, 30));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\unlocked-icon.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\person-icon.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 30, 40));

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("         Giriş yap");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 100, 40));

        jLabel4.setBackground(new java.awt.Color(186, 79, 84));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("    X ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 50, 40));

        userTF1.setBackground(new java.awt.Color(186, 79, 84));
        userTF1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        userTF1.setForeground(new java.awt.Color(255, 255, 255));
        userTF1.setText("Kullanıcı adı");
        userTF1.setBorder(null);
        userTF1.setCaretColor(new java.awt.Color(255, 255, 255));
        userTF1.setCaretPosition(8);
        userTF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTF1FocusGained(evt);
            }
        });
        userTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTF1ActionPerformed(evt);
            }
        });
        jPanel3.add(userTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTFActionPerformed

    private void userTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTFFocusGained
        userTF.setText("");
    }//GEN-LAST:event_userTFFocusGained

    private void passTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTFFocusGained
        passTF.setText("");
    }//GEN-LAST:event_passTFFocusGained

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void userTF1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTF1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF1FocusGained

    private void userTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTF1ActionPerformed

    private void a1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_a1FocusGained
       a1.setText("");
    }//GEN-LAST:event_a1FocusGained

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void s1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusGained
       s1.setText("");
    }//GEN-LAST:event_s1FocusGained

    private void k1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_k1FocusGained
        k1.setText("");
    }//GEN-LAST:event_k1FocusGained

    private void k1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        try{
            
            String host = "jdbc:mysql://localhost:3306/ogrenci_db";
            String uName = "root";
            String uPass= "05317312193En.";

            Connection con = DriverManager.getConnection(host,uName,uPass);
            String ad=a1.getText();
            String kul=k1.getText();
            String sif=s1.getText();

            Statement stmt = con.createStatement();
            String Sorgu = "INSERT INTO ogrenci_db.new_table (AD,KULLANICI,SIFRE)VALUES (" + "'" + ad + "'," + "'" + kul+ "'," + "'" + sif+ "')";//yeni kayit icin degerler eklenir

            stmt.executeUpdate(Sorgu);
            a1.setText(" ");
            k1.setText(" ");
            s1.setText(" ");

        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, "HATA");}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO adtry
        try {//kullanıcı giriş yeri

            String host = "jdbc:mysql://localhost:3306/ogrenci_db";
            String uName = "root";
            String uPass= "05317312193En.";

            Connection con = DriverManager.getConnection(host,uName,uPass);
            String kul2=userTF.getText();
            String sif1=passTF.getText();

            Statement stmt = con.createStatement();

            String sql="SELECT * FROM ogrenci_db.new_table WHERE KULLANICI='"+kul2+"' and SIFRE ='"+sif1+"'";
            ResultSet rs=stmt.executeQuery(sql);
            if(rs.next()){
                dispose();
                NewJFrame11 x= new NewJFrame11();
                x.show();//masa ekleme,silme ekrani acilir
            }
            else{
                JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre hatalı!");
                userTF.setText("");//
                passTF.setText("");
            }
        }

        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, "HATA");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField k1;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JPasswordField s1;
    private javax.swing.JTextField userTF;
    private javax.swing.JTextField userTF1;
    // End of variables declaration//GEN-END:variables
}
