/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantsytem;

/**
 *
 * @author User
 */
public class masaEkle extends javax.swing.JFrame {

    /**
     * Creates new form masaEkle
     */
    public masaEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        masa1 = new javax.swing.JButton();
        masa2 = new javax.swing.JButton();
        masa3 = new javax.swing.JButton();
        masa4 = new javax.swing.JButton();
        masa5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        masa9 = new javax.swing.JButton();
        masa8 = new javax.swing.JButton();
        masa7 = new javax.swing.JButton();
        masa6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\Restaurant-Blue-2-icon (1).png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 70));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("       Çıkış");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 70, 40));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("              Masa Görüntüle");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, 30));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("              Masa Ekle");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 257, 150, 30));

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Masaüstü\\shop-icon.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 0, 190, -1));

        jLabel6.setBackground(new java.awt.Color(186, 79, 84));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("    X ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 40));

        masa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa1.setText("1");
        masa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa1MouseClicked(evt);
            }
        });
        jPanel3.add(masa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 60));

        masa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa2.setText("2");
        masa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa2MouseClicked(evt);
            }
        });
        jPanel3.add(masa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, 60));

        masa3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa3.setText("3");
        masa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa3MouseClicked(evt);
            }
        });
        jPanel3.add(masa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 80, 60));

        masa4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa4.setText("4");
        masa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa4MouseClicked(evt);
            }
        });
        masa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa4ActionPerformed(evt);
            }
        });
        jPanel3.add(masa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, 60));

        masa5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa5.setText("5");
        masa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa5MouseClicked(evt);
            }
        });
        jPanel3.add(masa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, 60));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("10");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, 60));

        masa9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa9.setText("9");
        masa9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa9MouseClicked(evt);
            }
        });
        masa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa9ActionPerformed(evt);
            }
        });
        jPanel3.add(masa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 80, 60));

        masa8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa8.setText("8");
        masa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa8MouseClicked(evt);
            }
        });
        masa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa8ActionPerformed(evt);
            }
        });
        jPanel3.add(masa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, 60));

        masa7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa7.setText("7");
        masa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa7MouseClicked(evt);
            }
        });
        masa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masa7ActionPerformed(evt);
            }
        });
        jPanel3.add(masa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 80, 60));

        masa6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        masa6.setText("6");
        masa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masa6MouseClicked(evt);
            }
        });
        jPanel3.add(masa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        log m=new log();
        m.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        NewJFrame11 m=new NewJFrame11();
        m.show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        masaEkle m=new masaEkle();
        m.show();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void masa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa2MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("2");
    }//GEN-LAST:event_masa2MouseClicked

    private void masa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa3MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("3");
    }//GEN-LAST:event_masa3MouseClicked

    private void masa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa1MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("1");
    }//GEN-LAST:event_masa1MouseClicked

    private void masa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa5MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("5");
    }//GEN-LAST:event_masa5MouseClicked

    private void masa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa6MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("6");
    }//GEN-LAST:event_masa6MouseClicked

    private void masa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa7MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("7");
    }//GEN-LAST:event_masa7MouseClicked

    private void masa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa7ActionPerformed

    private void masa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa8MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("8");
    }//GEN-LAST:event_masa8MouseClicked

    private void masa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa8ActionPerformed

    private void masa9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa9MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("9");
    }//GEN-LAST:event_masa9MouseClicked

    private void masa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa9ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("10");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void masa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masa4MouseClicked
        setVisible(false);
        NewJFrame m=new NewJFrame("4");
    }//GEN-LAST:event_masa4MouseClicked

    private void masa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masa4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masaEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masaEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masaEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masaEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masaEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton masa1;
    private javax.swing.JButton masa2;
    private javax.swing.JButton masa3;
    private javax.swing.JButton masa4;
    private javax.swing.JButton masa5;
    private javax.swing.JButton masa6;
    private javax.swing.JButton masa7;
    private javax.swing.JButton masa8;
    private javax.swing.JButton masa9;
    // End of variables declaration//GEN-END:variables
}
