/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantsytem;

import java.awt.Color;
import javax.swing.JTextField;
import java.awt.TextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame  {
    public static int a=999;
    String i;
    /**
     * Creates new form Form
     */
    public NewJFrame(String i) {
        this.i=i.toString();
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        
        
        
    }
    
        public NewJFrame() {
        
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);


        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        ts2 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        ts3 = new javax.swing.JCheckBox();
        ts8 = new javax.swing.JCheckBox();
        ts4 = new javax.swing.JCheckBox();
        ts5 = new javax.swing.JCheckBox();
        ts6 = new javax.swing.JCheckBox();
        ts7 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));
        jPanel1.setPreferredSize(new java.awt.Dimension(913, 422));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb1.setText("Mantı: 30TL");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 60, 93, -1));

        cb2.setText("Pide: 20TL");
        jPanel1.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 101, 93, -1));

        cb3.setText("Kebap: 40TL");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        jPanel1.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 150, 93, -1));

        ts2.setText("Köfte : 40TL");
        jPanel1.add(ts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 247, 93, -1));

        cb4.setText("Kola: 10TL");
        jPanel1.add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 60, 108, -1));

        cb5.setText("Ayran: 5TL");
        jPanel1.add(cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 101, 108, -1));

        cb6.setText("Su: 5TL");
        jPanel1.add(cb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 150, 108, -1));

        ts3.setText("Çay: 5TL");
        jPanel1.add(ts3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 191, 108, -1));

        ts8.setText("Türlü: 40TL");
        jPanel1.add(ts8, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 191, 93, -1));

        ts4.setText("Kahve: 15TL");
        jPanel1.add(ts4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 247, 110, -1));

        ts5.setText("Puding: 20TL");
        jPanel1.add(ts5, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 60, 100, -1));

        ts6.setText("Baklava: 30TL");
        jPanel1.add(ts6, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 109, 100, -1));

        ts7.setText("Sütlaç: 20TL");
        jPanel1.add(ts7, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 150, 100, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("EKLE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 288, 116, 52));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Toplam : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 360, -1, -1));

        tf1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        tf1.setToolTipText("Masa no giriniz");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 358, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        int tutar=0;
        
        
        Menu menu1=new Menu();//menu nesnesi tanimlanir
        Menu yemek1=new Food(30,"Mantı","Ana Yemek");//menudeki yemekler tanimlanir
        Menu yemek2=new Food(20,"Pide","Ana Yemek");
        Menu yemek3=new Food(40,"Kebap","Ana Yemek");
        Menu yemek4=new Food(40,"Türlü","Ana Yemek");
        Menu yemek5=new Food(40,"Kofte","Ana Yemek");
        Menu yemek6=new Food(20,"Puding","Tatli");
        Menu yemek7=new Food(30,"Baklava","Tatli");
        Menu yemek8=new Food(20,"Sutlac","Tatli");

        Menu icecek1=new Beverage(10,"Kola",200);//menudeki icecekler tanimlanir
        Menu icecek2=new Beverage(5,"Ayran",250);
        Menu icecek3=new Beverage(5,"Su",200);
        Menu icecek4=new Beverage(5,"Cay",200);
        Menu icecek5=new Beverage(15,"Kahve",200);
        menu1.yemekAdd((Food) yemek1);//yemekler ve arrayliste eklenir
        menu1.yemekAdd((Food) yemek2);
        menu1.yemekAdd((Food) yemek3);
        menu1.yemekAdd((Food) yemek4);
        menu1.yemekAdd((Food) yemek5);
        menu1.yemekAdd((Food) yemek6);
        menu1.yemekAdd((Food) yemek7);
        menu1.yemekAdd((Food) yemek8);
        menu1.icecekAdd((Beverage) icecek1);
        menu1.icecekAdd((Beverage) icecek2);
        menu1.icecekAdd((Beverage) icecek3);
        menu1.icecekAdd((Beverage) icecek4);
        menu1.icecekAdd((Beverage) icecek5);

        if(cb1.isSelected()){//checkbox secildiginde menu classından secilenin fiyati get komudu ile getilir
            tutar=(int) (tutar+yemek1.getFiyat());
        }
        if(cb2.isSelected()){
            tutar=(int) (tutar+yemek2.getFiyat());
        }
        if(cb3.isSelected()){
            tutar=(int) (tutar+yemek3.getFiyat());
        }
        if(ts2.isSelected()){
            tutar=(int) (tutar+yemek4.getFiyat());
        }
        if(ts2.isSelected()){
            tutar=(int) (tutar+yemek5.getFiyat());
        }
        if(ts5.isSelected()){
            tutar=(int) (tutar+yemek6.getFiyat());
        }
        if(ts6.isSelected()){
            tutar=(int) (tutar+yemek7.getFiyat());
        }
        if(ts7.isSelected()){
            tutar=(int) (tutar+yemek8.getFiyat());
        }
        if(cb4.isSelected()){
            tutar=(int) (tutar+icecek1.getFiyat());
        }
        if(cb5.isSelected()){
            tutar=(int) (tutar+icecek2.getFiyat());
        }
        if(cb6.isSelected()){
            tutar=(int) (tutar+icecek3.getFiyat());
        }
        if(ts3.isSelected()){
            tutar=(int) (tutar+icecek4.getFiyat());
        }
        if(ts4.isSelected()){
            tutar=(int) (tutar+icecek5.getFiyat());
        }
        tf1.setText(String.format("%d",tutar));
        try{

            KayitEkle(tutar,this.i);//Masanın ve masa hesabının veritabanına eklenme fonksşyonu

        }
        catch(Exception err){

            JOptionPane.showMessageDialog(null, "HATA");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered
                                   

                               

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                
            }
        });
    }
        private void KayitEkle(int tutar, String masa){
        
        try
        {
           
            String host = "jdbc:mysql://localhost:3306/ogrenci_db";
            String uName = "root";
            String uPass= "05317312193En.";
            boolean flag=true;
            Connection con = DriverManager.getConnection(host,uName,uPass);
            Statement stmt = con.createStatement();
            String sorgu = "SELECT * FROM ogrenci_db.depo";
            ResultSet rs =stmt.executeQuery(sorgu);
            
            
            while (rs.next()) {
                
                String masam4 = rs.getString("MASA");
                int tutar4 = Integer.parseInt(rs.getString("TUTAR"));
                if(masam4.equals(masa)){// secilen masa veritabanında alınır
                     JOptionPane.showMessageDialog(null, "Masa Dolu");
                     flag=false;
                     masaEkle m=new masaEkle();
                setVisible(false);
                m.show();
                }
               
                
                             
            }
            if(flag){
                
                String sqlkod = String.format("INSERT INTO depo (MASA,TUTAR)VALUES( '%s',%d)",masa,tutar);//masa ekleme 
                
            stmt.executeUpdate(sqlkod);
            
            JOptionPane.showMessageDialog(null, String.format("Masa Eklendi\n hesap özeti : %d",tutar));
            masaEkle m=new masaEkle();
                setVisible(false);
                m.show();
            }
            
        }
        
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, "Masa Eklenemedi");
        }
        
        
      
    }
     private void KayitBak(String masa){
        String sorgu = "SELECT * FROM DEPO";
        
        try {
            String host = "jdbc:derby://localhost:1527/host";
            String uName = "ebs";
            String uPass= "123";
            
            Connection con1 = DriverManager.getConnection(host,uName,uPass);
            Statement stmt = con1.createStatement();
            int kalan=0;
            ResultSet rs =stmt.executeQuery(sorgu);
            
            while (rs.next()) {
                
                String masam = rs.getString("MASA");
                int tutar = Integer.parseInt(rs.getString("TUTAR"));
                if(masam.equals(masa)){// secilen masa veritabanında alınır
                     System.out.println(tutar);     
                    a=tutar;
                     
                }
                
                
                System.out.println("Masa : " + masam + " Tutar: " + tutar);                
            }
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Masa Bakılamadı");
        }
    
        
    }
    
      private void KayitSil(String masa){
     
     
        try
        {
            String host = "jdbc:derby://localhost:1527/host";
            String uName = "ebs";
            String uPass= "123";
            
            Connection con1 = DriverManager.getConnection(host,uName,uPass);
            Statement stmt = con1.createStatement();
            
            
            
            String sqlkod1 = String.format("DELETE FROM DEPO WHERE MASA = ('%s')",masa);//secilen masa silinir
            stmt.executeUpdate(sqlkod1);
            JOptionPane.showMessageDialog(null, "Masa Silindi");
           
        }
        
        catch(SQLException err)
        {
            JOptionPane.showMessageDialog(null, "Masa Silinmedi");
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf1;
    private javax.swing.JCheckBox ts2;
    private javax.swing.JCheckBox ts3;
    private javax.swing.JCheckBox ts4;
    private javax.swing.JCheckBox ts5;
    private javax.swing.JCheckBox ts6;
    private javax.swing.JCheckBox ts7;
    private javax.swing.JCheckBox ts8;
    // End of variables declaration//GEN-END:variables


}
